- glfs.c
This fixes the wce tcmu_get_attribute() error check, which currently has
a cut-n-paste bug.
> gluster: fix tcmu_get_attribute error check

- Makefile
- glfs.c
A number of different ways to fix this.  Some may object with the use of a macro.  If not liking swizzle it another way, but this is currently a bug.
> Fix compiler warning and remove generated files on 'make clean'

- CMakeLists.txt
- qcow.c
- qcow.h
Adapted from the QEMU code.  Handles qcow version 1 with compression
(read only, copy-on-write expanded) and read-only backing images in
either qcow or raw format.  Encryption is intentionally not supported,
as it's a flawed design that has been deprecated in QEMU.
My plans are to extend this to qcow2 next, but qcow was a good small
module to test porting from QEMU to tcmu-runner.
Signed-off-by: Chris Leech <cleech@redhat.com>
> QEMU QCoW version 1 handler

- .gitignore
- CMakeLists.txt
- api.c
- consumer.c
- libtcmu.c
- main.c
- tcmu-runner.h
Today, tcmu-runner owns the worker threads, thus forcing the users' code into the
plugin structure. This certainly works for minimal examples, but prevents any kind
of embedding into larger 3rd-party applications.
Production-grade applications generally have their own threading structure and want
to deal with socket/file/tcmu notifications in an async way. As such, I just need a
minimal library that handles device opening and command parsing.
There are several API sets now:
- the API each plugin must implement (unchanged, see tcmu_handler)
- the API available to the plugin (api.c)
- the API the host process must implement (debug functions today)
- the minimal API tcmu_lib will provide (a new concept, builds on api.c)
> Factored out SCSI request processing

- main.c
This fixes the following error when starting up tcmu-runner:
root@debian-jessie:/home/vagrant/lio/tcmu-runner$ sudo ./tcmu-runner 
libkmod: ERROR ../libkmod/libkmod-module.c:531 kmod_module_new_from_lookup: An empty list is needed to create lookup
couldn't load module
root@debian-jessie:/home/vagrant/lio/tcmu-runner$
Environment:
vagrant@debian-jessie:~/lio/tcmu-runner$ dpkg -l libkmod-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-================================================
ii  libkmod-dev:amd64     18-3            amd64 …
> Initialize "list" output parameter for kmod_module_new_from_lookup()

- .gitignore
- CMakeLists.txt
- README.md
- api.c
- consumer.c
- file_example.c
- glfs.c
- libtcmu.c
- libtcmu.h
- libtcmu_common.h
- libtcmu_priv.h
- main-syms.txt
- main.c
- qcow.c
- tcmu-runner.h
The goal for this branch is to flip things around so TCMU can be used as a library by existing applications such as QEMU or others that have their own event loop. This will require that libtcmu give the client the file descriptors to wait on. This allows the client to have control over the whole spectrum of parallelization options, from every device being handled by a single thread, to each device being given its own thread, or something in between.
libtcmu would handle parsing netlink and also registering as a handler with tcmu-runner over DBus, as well as handling the low-level parts of the TCMU udev interface and supplying basic SCSI command emulation routines that clients can use if desired.
EDIT: libtcmu currently does no DBus (it's all in tcmu-runner). In the future it will make …
> Shared library support

- consumer.c
- libtcmu.c
- libtcmu_priv.h
- there was a clash between errp() functions
+ these overloads are legal in C++
+ yet might be considered ODR in C (assuming the language uses the term)
- the printing function must be stashed away
+ and passed in
> Corrected debug-level printing

- CMakeLists.txt
- api.c
- libtcmu.c
- libtcmu.h
- libtcmu_priv.h
- there is no need to have two types and cast between them
- a forward declaration is enough for the public sites, while the private
sites can have a full one
> Simplified context handlers a bit

- api.c
- consumer.c
- file_example.c
- glfs.c
- libtcmu.c
- libtcmu.h
- libtcmu_common.h
- libtcmu_priv.h
- main.c
- qcow.c
- tcmu-runner.h
- the handler can now return TCMU_ASYNC_HANDLED
- tcmulib_get_next_command() now always copies iovec and cdb from the command ring
to the tcmulib_cmd. The returned command can be safely used in async handler.
- rename get_cdb_length() to tcmu_get_cdb_length() and add support for variable-length CDB.
> Async IO API proposal:

- consumer.c
- libtcmu.c
- libtcmu.h
- main.c
Fix a race condition result in userspace was blocked infinitely
The currently kernel/userspace command handling logic is:
```
while (1) {
while (tcmulib_get_next_command()) {
// handle
}
if (complete) {
read(fd); // ack that userspace received event
write(fd); // ack that userspace complete the event
}
}
```
But there is a window between finish the searching for next command
`tcmulib_get_next_command()` and mark the command as received (`read(fd)` in
`tcmulib_processing_complete()`), because we handle the command first then ack it
later. We won't know if there are commands sent from kernel space
after tcmulib_get_next_command() return false but before we read(fd) to ack the
event, then we would ack the receiving of new commands by mistake. Then polling
the uio fd would be blocked until …
> Fix a race condition result in userspace was blocked infinitely

- qcow.c
Basic qcow2 support, handles the refcount tables.  Also fixes up some issues when request iovecs are not being sector aligned.  Might be some issues to work out when faced with snapshots still.
> qcow2 image file support

- api.c
- consumer.c
- libtcmu.c
- libtcmu.h
- libtcmu_priv.h
A couple fixes to let me correctly link to libtcmu with the following dummy application (configure detection snippet):
#include <stdio.h>
#include <libtcmu.h>
int main(int argc, char **argv)
{
struct tcmulib_context *ctx = tcmulib_initialize(NULL, 0, NULL);
return ctx != NULL;
}
> libtcmu.h: Don't include scsi_defs.h

- libtcmu.c
> libtcmu: Remember to close fd before return in is_uio

- glfs.c
I'm using glfs as the basis for a new handler and came across these. They are untested but look pretty straightforward.
> glfs: fix some WRITE error paths

- main.c
The commit is extracted from the RFC of yesterday. It is independent so we can just merge it.
> tcmu-runner: Simplify on_check_config DBus return value

- CMakeLists.txt
glfs and qcow handlers are installed under
${CMAKE_INSTALL_LIBDIR}/tcmu-runner, but tcmu-runner_HANDLER_PATH
currently carries a "/usr/" prefix. As a result the tcmu-runner binary
can't locate the handlers unless an explicit --handler-path parameter
is specified.
> build: fix tcmu-runner_HANDLER_PATH

- CMakeLists.txt
- qcow.c
The fallocate() call in qcow.c uses FALLOC_FL_ZERO_RANGE,
but this macro is defined in <linux/falloc.h> on some systems,
so make this inclusion possible with an ifdef.
See Issue #52
> Alloc inclusion of falloc.h when needed. (Issue #52)

- libtcmu.c
- libtcmu_priv.h
It's not possible to pass variadic argument to another function, so macro has
to be used.
> Fix tcmu_errp() for variadic argument

- libtcmu.c
Hi Andy,
I've tried to restart the TCMU handling process within the process, and found some issues.
The most serious one is that since we didn't close or unmap UIO fd in any situation after start, it will result in use-after-free of uio_info struct inside kernel, potentially can cause kernel panic.
Also, there are other steps need to be done to properly teardown the TCMU setup in order to restart it. I've included them in this PR.
Thanks!
> Address the restart of TCMU within the process

- CMakeLists.txt
cmake currently writes tcmuhandler-generated.* and version.h into the
build directory, which sees compilation fail if cmake is invoked from
outside the source directory (build_dir != source_dir).
Bug: https://github.com/open-iscsi/tcmu-runner/issues/62
> build: fix builds done outside of source directory

- libtcmu-register.c
- libtcmu.c
The documentation of tcmulib_handler.check_config says "this function is
optional", handlers don't implement this should be handled gracefully.
> Don't call handler->check_config if NULL

- CMakeLists.txt
On my ubuntu 14.04 I got following error on the fresh building:
/home/yliu/tcmu-runner/qcow.c: In function ‘qcow2_block_alloc’:
/home/yliu/tcmu-runner/qcow.c:1008:27: error: ‘FALLOC_FL_ZERO_RANGE’ undeclared (first use in this function)
ret = fallocate(s->fd, FALLOC_FL_ZERO_RANGE, cluster, s->cluster_size);
^
/home/yliu/tcmu-runner/qcow.c:1008:27: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/handler_qcow.dir/qcow.c.o] Error 1
make[1]: *** [CMakeFiles/handler_qcow.dir/all] Error 2
This is because we don't pass on HAVE_LINUX_FALLOC, which can be automatically
detected by cmake module function, to compiler.
So the reasonable fix is to add the include-file-check.
Signed-off-by: Liu Yuan <liuyuan@cmss.chinamobile.com>
> build: fix failure on ubuntu

- libtcmu.c
the device is freed in thread cleanup function,  this fd cannot be closed since it is not a valid fd
Signed-off-by: xinxin shu <shuxinxin@chinac.com>
> libtcmu: free tcmu_device after dev->fd is closed

- CMakeLists.txt
This will create a new target in the Makefile, allowing devvers to enjoy cscope
utility just by typing 'make cscope'.
'make clean' will also clean up the intermediate cscope files.
Signed-off-by: Liu Yuan <liuyuan@cmss.chinamobile.com>
> build: add cscope support

- CMakeLists.txt
- README.md
- file_example.c
- glfs.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- main.c
- qcow.c
- rbd.c
- tcmu-runner.h
Currently storage engine plugins tightly couple with the iscsi command handling
which not only duplicate lines of code but also make plugin writing painful.
we can avoid it by adding one more indirction, a generic_handle_cmd(), which is
optional and can coexist with current command handling logic. With this added,
the command process can be split into two category:
1. one can register .handle_cmd to take the full control of command handling as
before
2. or else one can register .{read, write, flush} to only handle storage IO
stuff.
and then iscsi command handling can sit on top of the storage layer, meaning
that we can handle most of the commands without involving plugins, for e.g
COMPARE AND WRITE is implemented just by generic_handle_cmd().
What make it complex is how we deal with async …
> Introduce generic_handle_cmd() and add ceph rbd handler

- api.c
- qcow.c
The function tcmu_get_device_size() and tcmu_get_attribute() returns -EINVAL when not correct,but some caller compare it with -1,so fix it.
Signed-off-by: JianfeiHu hujianfei@cmss.chinamobile.com
> Fix some caller of tcmu_get_device_size() and tcmu_get_attribute()

- CMakeLists.txt
- main.c
- tcmu-synthesizer.c
- version.h.in
RHEL 7 only supports CMake 2.8, so ensure tcmu-runner can
be built within a RHEL 7 build environment.
> Support CMake 2.8 instead of CMake 3.0

- CMakeLists.txt
- api.c
- consumer.c
- file_example.c
- file_optical.c
- glfs.c
- libtcmu-register.c
- libtcmu.c
- libtcmu.h
- libtcmu_config.c
- libtcmu_config.h
- libtcmu_log.c
- libtcmu_log.h
- libtcmu_priv.h
- main.c
- qcow.c
- qcow.h
- qcow2.h
- rbd.c
- tcmu-runner.h
- tcmu-synthesizer.c
- tcmu.conf
This patch series add logger and system config support.
The logger feature:
For now the log messages will output to system logger. And the non-block feature will be supported in the later series.
The system config feature:
For now it will support 3 type options: int, string and boolean. If the options has been changed in config file, the tcmu-runner, consumer and tcmu-synthesizer daemons should be restarted.
And the dynamic reloading feature will be added later.
Thanks.
BRs
> Add logger and system config features support

- file_optical.c
> file_optical: Fix lba from uint32 to uint64.

- tcmu-runner.service
If tcmu-runner fails for any reason, systemd should restart it.
Signed-off-by: Steven Royer <seroyer@us.ibm.com>
> Restart tcmu-runner on failure

- consumer.c
- libtcmu_log.c
- libtcmu_log.h
- main.c
- tcmu-synthesizer.c
Add nonblock logger by using ring buffer. Log request is inserted into the rb as an array element firstly.A handler thread will fetch logs from the rb to output to syslog.
Output to stdout while log level is DEBUG is temporarily added in this patch.
Signed-off-by: Jianfei Hu <hujianfei@cmss.chinamobile.com>
> Add nonblock logger support

- libtcmu.c
- main.c
COMPARE_AND_WRITE in rbd.c is just an example (which will be overloaded once
ceph part is ready) about how we can pass down chose command to the specific
store.
Signed-off-by: Liu Yuan <liuyuan@cmss.chinamobile.com>
> runner: add command passthrough support for generic_handle_cmd

- qcow.c
This patch addresses tcmu_write_verify not working properly.
The caller needs to pass the length as a parm, otherwise the function doesnt
work properly, and the length will be 0. Thus the code does not run.
> tcmu-runner: write verify fix

- CMakeLists.txt
- api.c
- glfs.c
- libtcmu.c
- libtcmu_aio.c
- libtcmu_aio.h
- libtcmu_common.h
- libtcmu_priv.h
- libtcmu_store.c
- libtcmu_store.h
- qcow.c
- rbd.c
- tcmu-runner.h
These set of changes aims to conver RBD handlers read/write/flush operation asynchronous by making use of asynchronous librbd APIs. This involves changes to `generic_handle_cmd()` to handle `TCMU_ASYNC_HANDLED` return value by store callout methods. Furthermore, `compare_and_write` has been added as a store callout method though keeping the implementation same (read + write as of now, but rbd would make use of `cmpext` OSD op when ready).
> asynchronous rbd handler

- CMakeLists.txt
- api.c
- libtcmu.c
- libtcmu_aio.c
- libtcmu_aio.h
- libtcmu_common.h
- libtcmu_priv.h
- libtcmu_store.c
- libtcmu_store.h
- tcmu-runner.h
Bulk of the changes are in `libtcmu_store.c` source which has all the asynchronous implementation of multi-op commands. I think given the nature of changes, there should be have more code comments, especially regarding some rules on how to implement asynchronous multi-op commands. I have an half finished doc regarding the same which I'll try to include in this PR as a future update.
> asynchronous compound store operation

- libtcmu.c
- libtcmu_config.h
- libtcmu_log.c
- libtcmu_log.h
- main.c
- tcmu.conf
For the CDB debug messages, they will fill the logger buffer
full very quickly and will overwrite all the other err/warn/debug
messages.
Here just output the CDB debuginfo output to the stderr.
> logger: add tcmu_dbg_cdb() helper support

- libtcmu.c
> tcmu: Fix a bug with generic cmd missing read_capacity

- api.c
A six-byte CDB may contain a 21-bit LOGICAL BLOCK ADDRESS field.
> api: Fix a bug with parsing the 6-byte length format lba

- api.c
- libtcmu.c
libtcmu: Fix a bug with getting variable type CDB length
api: Use the group code the do the CDB formats check
At the same time this could simplify the code and be more readable.
libtcmu: Convert to use tcmu_get_cdb_length helper
> Misc for CDB formats length

- api.c
- file_example.c
- libtcmu_common.h
When the current file size is less than its real capacity for
some reason, such just after created by file_check_config,
the preadv will return 0, and the file_read will in a infinite
loop.
Then try to zero the iovecs left.
> file_example: Fix endless reading the file.

- file_optical.c
- main.c
Just encountered this when testing the old and new versions at
the same by renaming the old handlerXX.so to handlerYY.so, and
forgot to make clean or remove them. But this won't report any
warning or error message.
Maybe my way doing the test is not very wise, but this could be
a potential bug.
> runner: add possible repetitive handler registerring check.

- CMakeLists.txt
- libtcmu_log.c
- libtcmu_log.h
- libtcmu_time.c
- libtcmu_time.h
Add multi-output support, file/stdout/sysylog are currently
supported and enabled in default.
Log format is made as "timestamp pid [log_level] msg".
The syslog level is INFO when others are DEBUG in default, and 
log level config should be moved to config file later instead the 
default configuration. 
Signed-off-by: Jianfei Hu hujianfei@cmss.chinamobile.com
Signed-off-by: Xiubo Li lixiubo@cmss.chinamobile.com
> Add multi-output support

- CMakeLists.txt
- alua.c
- alua.h
- api.c
- configfs.c
- consumer.c
- libtcmu_common.h
- libtcmu_log.c
- libtcmu_log.h
- rbd.c
- scsi_defs.h
- tcmu-runner.h
- tcmu-synthesizer.c
- tcmur_cmd_handler.c
Very limited ceph rbd failover/failback support using linux and windows initiators. You can export N images as SCSI LUNs through M targets. The major limitation is that you can only have one enabled port per LUN per node. In targetcli, if you were to export an image, testtcmulock, through one HA iscsi target that spans 2 nodes (so running LIO on 2 nodes and each node is exporting a iscsi target ion.1999-09.com.tcmu:alua) and each node has a iscsi portal, it would look like this on one node. On the other node, you would have the opposite tpgs enabled/disabled:
targetcli ls
o- / .................................................................... [...]
o- backstores ......................................................... [...]
| o- block ............................................. …
> ceph rbd ALUA failover/failback support

- rbd.c
We cannot reopen the image from the report callout because
another node could have taken the lock while IO is in flight
and at the same time the network to ceph could go down.
To be safe we need that IO to fail from the blacklisting before
we can reopen the image.
> rbd: do not reopn image from report callout

- qcow.c
Previously, if you mapped a raw file using user:qcow, it would display
an error message saying "bad magic" with a stale errno message.  Now
make it clear that this may be expected if it's a raw file.
Signed-off-by: Steven Royer <seroyer@us.ibm.com>
> qcow: Clarify bad magic error message

- libtcmu_config.c
- libtcmu_log.c
This convert to use darray for the tcmu_options.
The following is the new helper to add and use the config feature:
/*
* System config for TCMU, for now there are only 3 option types supported:
* 1, The "int type" option, for example:
*	log_level = 2
*
* 2, The "string type" option, for example:
*	tcmu_str = "Tom"  --> Tom
*    or
*	tcmu_str = 'Tom'  --> Tom
*    or
*	tcmu_str = 'Tom is a "boy"' ---> Tom is a "boy"
*    or
*	tcmu_str = "'T' is short for Tom" --> 'T' is short for Tom
*
* 3, The "boolean type" option, for example:
*	tcmu_bool
*
* ========================
* How to add new options ?
*
* Using "log_level" as an example:
*
* 1, Add log_level member in:
*	struct tcmu_config {
*		int log_level;
*	};
*    in file libtcmu_config.h.
*
* 2, Add the following option in "tcmu.conf" …
> config: Convert to use darray and prepare for dynamic reloading

- api.c
Since the runner has already supported the CAW command, enable it.
If the MAXIMUM COMPARE AND WRITE LENGTH field, which in "SCSI Commands
Reference Manual" the section "Block Limits VPD Page (B0h)" set to
zero, means disable the CAW command.
> api: Enable COMPARE_AND_WRITE command

- tcmur_cmd_handler.c
This will allow the handlers could handle part commands through its
own ways firstly, and then try to handle the other through the
generic methods.
This will be helpful for some case, for example the XCOPY command:
The runner could implement one generic method by using handle_read()
and handle_write(), and the device could also implement its own
higher efficiency ways to do this, and the other handlers could fall
back to the generic methods.
Generically, if the generic command handle callout could handle the
specify commands correctly and hasn't any lower efficiency problem,
the handlers shouldn't implement it again.
For the ->handle_cmd callout by handlers, it should obey a rule that
only when the cmds are not supported by it should return
TCMU_NOT_HANDLED. Then the runner will try to …
> tcmur: Allow the handlers to handle the cmds through its own method 

- api.c
Prepare for the UNMAP command and for now in this VPD code the
UNMAP and Write Same UNMAP are both disabled.
They will be enabled later when needed.
> api: Add Logical Block Provisioning VPD page (B2h) support

- api.c
- scsi_defs.h
- tcmur_cmd_handler.c
This adds emulate xcopy support in tcmur and then enable it.
Tested Evironment:  ESXI 5.5
Backstore: file_example
> runner: Add Emulate xcopy support

- api.c
- libtcmu_common.h
- tcmur_cmd_handler.c
This will add a emulator for WRITE_SAME_16 command in runner. For
now the unmap option is not supported, and will be added later
when needed.
The Write Same Not Zero bit is set to one, and will be added later.
> tcmur: Add WRITE_SAME_16 command support

- api.c
- file_example.c
- glfs.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- main.c
- qcow.c
- rbd.c
This patchset fixes the calculation for the max xfer size and allows handlers like rbd to set their preferred value.
> fix IO max xfer limits

- main.c
- tcmur_cmd_handler.c
Also will fix some debug messages who are missing '\n'.
Such as the following, it will be a little hard to read:
[DEBUG] dev_added:630 lun1: Got block_size 512, size in bytes 10737418242017-05-21 11:33:45.844 30321 [DEBUG] file_open:103 : config file/file1
> runner: Convert to _dev_ helper and fix debug message

- libtcmu_common.h
- tcmur_cmd_handler.c
For the FORMAT_UNIT write options, the default length is 1MB and
this will round it up to the device's maximum xter length.
Then we can make sure that all the requests/BIO in IO queue is full.
> tcmur: format unit make sure the write length is muti of max_xfer_length 

- main.c
In some environments (ex: containers) modules dir doesn't exist, in such cases
the load_module job is left to admin.
This patch checks if modules dir exist before a kmod lookup.
> load_module: defend on modules directory

- glfs.c
- libtcmu.c
FirstCommit:
It seems like there is still one possibility for use-after-free in glfs handler when tcmu-runner is started when the gluster volume is not running. This is the trace we get in AddressSanitizer:
==1343==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300000dc30 at pc 0x7fd8ab4fb93f bp 0x7fff4a7eddf0 sp 0x7fff4a7edde0
READ of size 8 at 0x60300000dc30 thread T0
2017-05-28 07:58:13.930 1343 [ERROR] glfs_check_config:453 : tcmu_create_glfs_object failed
#0 0x7fd8ab4fb93e in gluster_free_server /root/tcmu-runner/glfs.c:270
#1 0x7fd8ab4fcc50 in glfs_check_config /root/tcmu-runner/glfs.c:480
#2 0x7fd8b15330a4 in add_device /root/tcmu-runner/libtcmu.c:243
#3 0x7fd8b1534500 in open_devices /root/tcmu-runner/libtcmu.c:436
#4 0x7fd8b1534c5f in tcmulib_initialize …
> Fix use-after-free bugs found 

- glfs.c
If glfs_check_config() is called with a cfgstring that doesn't have '/'
then it can lead to crash as ptr 'hosts' is not initialized to NULL.
Fixing that in this commit.
Signed-off-by: Pranith Kumar K <pkarampu@redhat.com>
> Avoid free of uninitialized ptr

- glfs.c
1) Free partially allocated structure on failures
Instead of returning -ENOMEM use 'goto fail' which
is cleaning up partially allocated structure.
2) Fix use-after-free
We need to set *hosts = NULL as well in case of failures.
So pass hosts instead of &entry for gluster_free_server()
This is the asan trace:
==1482==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300000db70 at pc 0x7ffff0bfb93f bp 0x7fffffffc830 sp 0x7fffffffc820
READ of size 8 at 0x60300000db70 thread T0
#0 0x7ffff0bfb93e in gluster_free_server /root/tcmu-runner/glfs.c:270
#1 0x7ffff0bfc851 in tcmu_create_glfs_object /root/tcmu-runner/glfs.c:415
#2 0x7ffff0bfcda3 in tcmu_glfs_open /root/tcmu-runner/glfs.c:503
#3 0x417ced in dev_added /root/tcmu-runner/main.c:678
#4 0x7ffff6c12662 in add_device …
> Fix memory allocations in parse_imagepath

- tcmur_cmd_handler.c
For the XCOPY the maximum of the lbas copied each time will be min(src's hw_max_sectors, dst's hw_max_sectors).
[edit]This is different from the FORMAT_UNIT/WRITE_SAME, which are 1MB as default. Because for the XCOPY we want to support and compatible with the case that the src device and dst device have different types, for example src(rbd) --> dst(glfs), they may have different hw_max_sectors size.
> tcmur: Covert XCOPY to async

- libtcmu_common.h
- tcmur_cmd_handler.c
Since the WRITE SAME(10) and the WRITE SAME(16) are all pretty thesame code, this add the WRITE SAME(10) support.
Here just report full size limitation, which will be larger length than WS10(2-Bytes length) could support, and equals to WS16(4-Bytes length) could support. And the client will just figure out depend the specify write same commands and do the right thing.
> tcmur: Add WRITE SAME(10) support and remove the limitation of the max write length

- libtcmu_config.c
We open a PID filedescriptor, but never close it while a read() is interrrupted 
after reading some data to retrun -1.
So close the PID fd properly.
Signed-off-by: kai zhang <zhang.kai16@zte.com.cn>
> fixup fd leakage in libtcmu_config.c

- main.c
If the function tcmu_config_new return NULL，the process shoud exit，otherwise  it may cause coredump。
> fix: judge the function tcmu_config_new return value

- alua.c
In the function tcmu_emulate_report_tgt_port_grps，the group of alua_stauts should be  ALUA_STAT_ALTERED_BY_IMPLICIT_ALUA（0x2）instead of TPGS_ALUA_IMPLICIT（0x10）；
also in the function tcmu_emulate_set_tgt_port_grps，the group of alua_status should be ALUA_STAT_ALTERED_BY_EXPLICIT_STPG（0x1）。
> fix the group's alua_status in emulate rtpg and stpg

- libtcmu_log.c
tcmu-runner message in system log display as:
Jul  7 03:21:55 localhost ,o|: load_our_module:533 : Inserted module 'target_core_user'
The reason is that the first parameter 'ident' that calls openlog in the open_syslog function is a local variable. When calling syslog to print a specific message, the address pointed to by the 'ident' pointer may already be used by other programs, so there may be Garbled.
In the call openlog parameter should be a string constant or NULL (the system automatically add program name).
> fix the syslog message ident

- rbd.c
For clean up rados_shutdown()   is only necessary after rados_connect() has succeeded
> fix rados_connect failed in tcmu_rbd_image_open

- file_example.c
- libtcmu.c
- libtcmu.h
- libtcmu_common.h
- main.c
- tcmu-runner.h
These patches fix the issue where the kernel does not wait for userspace responses to add/delete/reconfigure, so if runner failed to execute them, the kernel will still end up updating its state. This can result in the kernel returning LUNs that are not setup in userspace, a race where close is called on the uio device after the kernel has done unregister, and the userspace and kernel device state out of sync.
These patches along with these kernel changes:
https://www.spinics.net/lists/target-devel/msg15706.html
fix the problem by having the kernel  wait for runner's response to these operations.
> Perform netlink operations synchronously and add reconfig support

- consumer.c
- libtcmu.c
- main.c
- target_core_user_local.h
It is kind of a pain to coordinate our upstream releases with
kernel headers releases. To allow users to be able to not have
to update kernel headers, but still use newer runner versions, this adds a
local target_core_user.h which will stay in sync with the upstream
kernel.
> [RFC] runner: add local target_core_user.h

- libtcmu.c
The patch:
commit 1028d483ccd3b138b2949c45e1a0d713aca98658
Author: Mike Christie <mchristi@redhat.com>
Date:   Thu Jun 22 03:39:05 2017 -0500
libtcmu/runner: add reconfig support v2
added/removed a couple debug log messages. This just cleans them up.
> libtcmu: cleanup log messages added/changed in reconfig patch

- glfs.c
When memory allocation failed, the allocated memory has to be freed
> fix memory leak in gluster_cache_add

- libtcmu.c
when open_devices() failed in tcmulib_initialize ，need to free ctx and unregistered tcmu_ops。
> libtcmu: free ctx in tcmulib_initialize

- libtcmu.c
After genl_register_family succeeds，the following operations failed should call genl_unregister_family。
> libtcmu: fix unregister genl ops in setup_netlink

- libtcmu_config.c
- libtcmu_config.h
- libtcmu_log.c
- main.c
Using the inotify, if write to the unwritable or crashed config file
forcely, the vi/vim will try to move and delete the old config file
and then recreate it again via the *.swp. When deleting the old
config file, the inotify watching handler will be removed from the
monitor too, so needs to add it back again.
> config: Add dynamic reloading support

- libtcmu.c
- libtcmu_log.c
fixed warnings: uninitialized format-truncation unused-results
> build: fix compiler warnings

- api.c
The supported VPD page list shall contain a list of all VPD page codes implemented by the logical unit in ascending order beginning with page code 00h
> tcmu: fix vpd0 inquiry response

- consumer.c
- file_example.c
- file_optical.c
- libtcmu.h
- libtcmu_config.c
- main.c
- qcow.c
- tcmu-runner.h
- tcmu-synthesizer.c
While doing a security audit of tcmu-runner I've come across these issues.
Rebased and squashed version of previous pull request:
https://github.com/open-iscsi/tcmu-runner/pull/193
> Rebased: Various security and functionality related bugfixes (multiple DoS, memory leaks)

- libtcmu_log.c
Bad cut and paste. Use vfprintf and not fprintf during early logging.
> runner: fix early logging

- main.c
by closing the IO channel, any pending data to be written will be flushed.
> main: close the glib io-channel

- libtcmu_config.c
- libtcmu_config.h
- main.c
The patches fix the following bugs:
1. runner segfault during dynamic reconfig.
2. memory leak for string opts.
@lxbsz You know the config code best, so please review.
> Config fixes

- api.c
The current buffer length 9 is too small， add pagecode 0x00 has been 10，so the initiator sends the vpd00 command to return the last byte to a random value。Taking into account the future expansion modified to 16.
> tcmu:fix the vpd00 inquiry response buffer length

- CMakeLists.txt
- api.c
- libtcmu.c
- qcow.c
Warn about C99 declaration after statement to make the code tidy and
more readable.
> cmake: add additional option -Wdeclaration-after-statement support

- qcow.c
The QCOW2_OFLAG_COPIED flag was being set on refcount
table entries allocated by tcmu-runner.  This caused
refcount lookups to fail for all clusters whose corresponding
refcount block was allocated by tcmu-runner.
Reviewed-by: Chris Leech <cleech@redhat.com>
Signed-off-by: Brad Warrum <bwarrum@us.ibm.com>
> Remove COPIED flag from qcow refcount table entry

- api.c
- consumer.c
- file_example.c
- glfs.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- qcow.c
- rbd.c
- tcmu-synthesizer.c
- tcmur_cmd_handler.c
Fixes for mode sense and the cache page:
1. Patch 1 fixes several issues in the mode sense handling of the allocation length field and short buffers.
2. Patch 2 allows handlers to report different WCE values.
3. The rest of the patches covert handlers to #2 so they report a WCE value they support.
> Mode sense

- glfs.c
O_SYNC makes IO a bit slow and as anyway we are ensuring the data
reaches onto nonvolatile disk with fdatasync() as part of flush op,
O_SYNC seems to be unworthy.
> glfs: remove O_SYNC

- alua.c
The error check here is actually the mistake by CDB data from scsi
client, should not be locally in target.
> alua: Fix MANAGEMENT PROTOCOL IN command sense code handling

- api.c
The logical block provisioning read zeros (LBPRZ) bit shall be set
to one if the LBPRZ field in VPD B2 is set to xx1b. The LBPRZ bit
shall be set to zero if the LBPRZ field is not set to xx1b.
> api: Enable LBPRZ in READ CAPACITY (16) command

- tcmur_cmd_handler.c
For the passthrough partially type handlers, likes the rbd handler,
will only passthrough some commands like XCOPY/CAW/WS..., the
.handle_cmd will be support in rbd's handler.
Sipmlify the code to let the developers wouldn't have to worry about
the handler is async or sync.
> tcmur: add handle_try_passthrough helper support

- api.c
- main-syms.txt
- rbd.c
- tcmur_cmd_handler.c
- tcmur_cmd_handler.h
1, rbd add write same support and with the UNMAP bit support.
2, write same emulator add UNMAP bit support.
3, limit the MAX WRITE SAME LENGTH to "hw_max_sectors" when both the unmap and write same are supported.
> rbd: Add write same support

- api.c
Since the INQUIRY cmd handler is always called by tcmur_cmdproc_thread,
created by dev->handler->added(), just after rhandler->open(). And
before the thread is alive all the possible dev->max_xfer_len setting
is done. So the code here is useless.
> api: remove extra useless code

- api.c
Here let assume hw_max_sectors == device's max discard sectors.
Till now we set the both OPTIMAL UNMAP GRANULARITY and GRANULARITY
ALIGNMENT to hw_max_sectors of the device.
The following example shows why we need the granularity alignment
in near feature:
If the unmap granularity == 64 and hw_max_sectors == 128. A request
that is submitted for 256 sectors 2...257 will be split in two: 2..129,
130..257. However, only 2 aligned blocks out of 3 are included in the
request, 128..191 may be left intact and not discarded. And here needs
one way to truncate to ensure good alignment to split into 2..127,
128..255, 256..257.
And for some case, maybe the initiators could use the alignment to
do the alignment just before submitting the request.
> api: VPD 0xB0 add UNMAP GRANULARITY ALIGNMENT support

- rbd.c
More detail please see: https://github.com/ceph/ceph/pull/16583
> rbd/write_same: make it compatible with lower version of librbd

- api.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- main.c
- tcmur_cmd_handler.c
NOTE: here we always asumme the OPTIMAL UNMAP GRANULARITY equals to UNMAP GRANULARITY ALIGNMENT, if not in feature and the align and split algorithm should be changed.
The next will add the alignment support in Write Same UNMAP.
> unmap: Align start lba and split large num blocks into optimal ones.

- CMakeLists.txt
- tcmu.conf_install.cmake.in
If there is a tcmu.conf do not overwrite it.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> build: don't overwrite tcmu.conf

- tcmu-runner.service
It looks like we are hitting the fd limit with setups having
lots of devices and with ceph/gluster setups with a medium/high
amount (only 40 with ceph and 1000 with gluster). This patch
just increases the default limit.
> tcmu-runner service: increase default file limit

- main.c
When new user who are not very familiar about the tcmu-runner,
his/her mostly will print the usage of this like:
./tcmu-runner -h
Failed to open file '/etc/tcmu/tcmu.conf', No such file or directory
This patch will make the usage visible even without intalling
the tcmu.conf file.
Signed-off-by: Zhuoyu Zhang <zhangzhuoyu@cmss.chinamobile.com>
> runner: make the usage visible without intalling tcmu.conf

- CMakeLists.txt
When libtcmu was created it was really early in the project and
missing lots of features. It is now difficult to maintain that API
and there may not be any users considering how many things
it was missing and we have not got any patches from non
tcmu-runner users in a long time.
The project will of course not change license and remain Apache
Version 2.0, so any one can just use the code in their own
project, but in future versions the stable libtcmu will not be
maintained.
If there are users, please speak up. It is a RFC patch, so I am open
to working something out. Are you using the netlink and uio ib functions,
but not the scsi and iovec ones in api.c?
> [RFC] libtcmu: do not install headers and drop libtcmu stable API

- README.md
Document:
1. CMAKE_INSTALL_PREFIX=/ will normally need to be used to install
tcmu-runner to where the systemd service requires it.
2. Add "make install"
> doc: add build info

- rbd.c
/data/tcmu-runner/rbd.c: In function ‘tcmu_rbd_service_status_update’:
/data/tcmu-runner/rbd.c:94:36: error: ‘state’ undeclared (first use in
this function)
ret = rados_service_update_status(state->cluster, status_buf);
^
> rbd: fix build error for rados_service_update_status()

- rbd.c
This will be very helpful when generating the cscope database, or
the cscope couldn't create the correct jump database for some function
like: rados_service_register().
> rbd: Add the header explicitly when needed

- tcmur_cmd_handler.c
When the target device is large enough, there will be too many noisy
split logs output.
These days I am testing the runner in large scale, there are to much
noisy log of this.
> tcmur/unmap_split: reduce the unmap split logs output

- api.c
- libtcmu_common.h
- main.c
Make the code more easy to debug.
> runner: scsi debug info convert to tcmu_dev_dbg_scsi_cmd()

- CMakeLists.txt
- rbd.c
This will make the code more save, because sometimes some warnings must be resolved or it will introduce bugs, like:
char *p;
if (cond)
p=q;
foo (p) 
.....
> Add -Werror for C_FLAGS

- alua.c
When the actual length is greater than the allocation length，the return data length filed of the rtpg response data is incorrect。
> tcmu:fix return data length of rtpg response data

- alua.c
The function tcmu_release_tgt_ports is called by function tcmu_free_alua_grp，so there is no need for explicit call tcmu_release_tgt_ports in tcmu_get_alua_grp()。
> tcmu:double free tgt_port in tcmu_get_alua_grp

- alua.c
When the function tcmu_get_alua_grp() return NULL,the function tcmu_get_alua_grps should return exception value ,that can avoid the upper call function re-release grp list。
> tcmu-runner:fix the exception return value for function tcmu_get_alua_grps()

- rbd.c
The rados osd op timeout must be longer than the timeouts to detect
unreachable OSDs (osd heartbeat grace + osd heartbeat interval) or
we will end up failing the transport connection when we just needed
to try a different OSD.
> rbd: Add timers check for cluster osd

- libtcmu_log.c
- main.c
@mikechristie @pkalever 
This is based on @pkalever's #178 PRs and then make this only configurable via the tcmu-runner's parameter.
1, @pkalever's #178 patch
2, make the rlimit openfile as one parameter
3, fix --tcmu-log-dir crash 
[EDIT]4, convert printf/fprintf to tcmu_xxx
Thanks,
Please review.
> tcmu-runner: rlimit openfile support via prarmeter

- rbd.c
fix rbd backstore device creation guideline in tcmu_rbd_cfg_desc
to make it more reliable to follow.
Signed-off-by: Zhang Zhuoyu <zhangzhuoyu@cmss.chinamobile.com>
> rbd:fix comment in tcmu_rbd_cfg_desc

- tcmur_cmd_handler.c
when client login, alua_implicit_transition always return with lock state 2
this patch just fix it.
Signed-off-by: Zhang Zhuoyu <zhangzhuoyu@cmss.chinamobile.com>
> alua:fix untrack when implicit transition not success

- main.c
Otherwise the device will not properly be closed when removed.
> main: set TCMUR_DEV_FLAG_IS_OPEN on successfully added devices

- libtcmu.c
- libtcmu_priv.h
cfgstring will look like,
test@192.168.124.208/block-store/c2d55250-9d9d-4965-bfa1-43ce1b3aa5fc (glfs)
The string can exceed 256 characters.
> libtcmu: fix cfgstring len

- glfs.c
- libtcmu_config.c
- libtcmu_config.h
- libtcmu_log.c
- libtcmu_log.h
- main.c
- tcmu.conf
1, add tcmu_logdir_check helper support 
2, fix and clean up the file output callout 
3, make tcmu_log_dir as static
4, move tcmu_logdir_create to log file and make it globally 
5,  fix error when making recursion directories 
6,  fix tcmu_conf_set_options 
7, make log dir configurable in tcmu.conf
> Logdir misc fix

- libtcmu.c
genl_ctrl_resolve_grp returns a negative error code[1] when failed to
look up the family object. This patch handles the negative error code.
[1] http://www.infradead.org/~tgr/libnl/doc/api/group__genl__ctrl.html
>    Numeric group identifier or a negative error code.
> libtcmu: handle error when netlink family group is not found

- libtcmu.c
> libtcmu: move genl_unregister_family to teardown_netlink

- be_byteshift.h
- file_optical.c
Fixes for compile errors when strict aliasing is on. Based on @bgly's patches in PR
https://github.com/open-iscsi/tcmu-runner/pull/273
> Fix file optical strict aliasing rules errors

- libtcmu.c
If dev->dev_name is uio1 but dev_name is uio10 we would
match it and return the dev for uio1.
This would cause problems for device removal because we would
leave the cmdproc running and accessing the uio device for
the device we wanted to shutdown (we shutdown the cmdproc
for uio1 instead of uio10). The kernel would then do
uio_unregister_device and free the uio device, but runner
could still be doing uio read/poll calls and cause crashes.
> libtcmu: fix name check for nl commands

- libtcmu-register.c
- libtcmu.h
- libtcmu_priv.h
- main.c
- tcmu-handler.xml
Fixes issues with dbus registration of tcmulib handlers.
tcmu-runner can now handle tcmulib processes that are killed or release
the dbus name for a specific subtype.
tcmulib daemon processes can now handle situations where the tcmu-runner
service becomes unavailable.
Signed-off-by: Bryant G. Ly bryantly@linux.vnet.ibm.com
Signed-off-by: Brad Warrum <bwarrum@us.ibm.com>
Prior to this change, the TCMUService1.HandlerManager1 DBus interface exposed two methods - RegisterHandler and UnregisterHandler.  The UnregisterHandler method did not have a corresponding tcmulib function.  When a tcmulib process died without calling the UnregisterHandler method, tcmu-runner would continue watching the bus name for all subtypes registered by the tcmulib process (on_register_handler() in main.c).  When …
> tcmulib dbus registration changes

- CMakeLists.txt
- README.md
- file_zbc.c
file_zbc.c implements a ZBC disk emulation using a file as backend
storage. The handler is compiled as handler_file_zbc.
handler_file_zbc can emulate both host aware and host managed disks.
In both cases, the LBA size, zone size and the number of conventional
zones can be configured through options in the configuration string.
The configuration, together with zone information (zone type, zone
condition, write pointer position, etc) are stored as metadata at the
beginning of the backstore file, invisibly to the user. The
configuration and state of the emulated device is thus retained
accross reboots.
The metadata in the backstore file is reinitialized (i.e. the device
configuration and state reset) if the specified backstore file does
not exist, if the metadata in the file is incorrect or …
> file_zbc: ZBC disk emulation handler

- rbd.c
Use ';' instead of '/' to separate options.
> rbd: fix the cfgstring setting

- tcmu-runner.service
This will enable the tcmu-runner service booted when the system
is up.
More detail please see:
https://www.freedesktop.org/software/systemd/man/bootup.html#
> systemd: setup the tcmu-runner in multi-user.target

- libtcmu_log.c
example:
[DEBUG_SCSI_CMD] tcmu_cdb_debug_info:1061 glfs/abc: 35 0 0 0 0 0 0 0 0 0
[...]
[DEBUG_SCSI_CMD] tcmu_cdb_debug_info:1061 rbd/xyz: 12 0 0 0 24 0
[...]
> log_internal: append device subtype if available

- install_dep.sh
For now only fedora/rhel/centos are support.
> runner: add install_dep.sh support

- file_zbc.c
error: format not a string literal and no format arguments [-Werror=format-security]
Signed-off-by: zhenwei.pi <zhenwei.pi@youruncloud.com>
> fix compiling error for gcc 5.3.1.

- install_dep.sh
https://download.ceph.com/rpm-jewel/rhel7/x86_64/
Before and Jewel Version, should be librbd1-devel.
https://download.ceph.com/rpm-kraken/el7/x86_64/
After and Kraken Version, should be librbd-devel.
> Fix ceph install deps to support [librbd1 librbd]-devel

- README.md
remove '.' after `cmake .`, which will be looks like `cmake ..` and will be confusing.
> README: update for supporting install_dep.sh

- file_zbc.c
Writes to conventional zones must not change the zone condition to
implicitly opened. Before calling __zbc_open_zone(), make sure that the
write target is a sequential zone.
Reported-by: Masato Suzuki <masato.suzuki@wdc.com>
Signed-off-by: Damien Le Moal <damien.lemoal@wdc.com>
> file_zbc: Do not implicitly open conventional zones

- README.md
- rbd.c
A custom Ceph config file can now be specified via a
"conf=/path/to/ceph.conf" optional within the cfgstring.
> rbd: new optional for specifying location of Ceph config file

- rbd.c
The bounce_buffer member variable also malloc buffer in tcmu_rbd_write。
So if ceph return write io error， but the target returned to the initiator of the ascq is ASC_READ_ERROR，and for wirte io, the processing is completed, do not need to continue copy buffer to iovec。
> rbd:member variable bounce_buffer of struct rbd_aio_cb can not distinguish r/w io

- tcmur_device.c
Warning it instead of output one error message, the error message
may confuse the users.
> tcmur: when tcmu_notify_lock_lost just warning it

- rbd.c
> rbd:free owners when rbd_lock_break timeout

- main.c
The unmap granularity alignment is advertised to initiators via the
Block Limits INQUIRY VPD, which is specified as follows (sbc3r25):
The UNMAP GRANULARITY ALIGNMENT field indicates the LBA of the first
logical block to which the OPTIMAL UNMAP GRANULARITY field applies.
The unmap granularity alignment is used to calculate an optimal unmap
request starting LBA as follows:
optimal unmap request starting LBA = (n × optimal unmap granularity)
+ unmap granularity alignment
Using a default unmap granularity alignment of max_xfer_length, which
is currently the case, means that the optimal unmap request starting LBA
is incorrectly staggered.
> runner: zero default unmap granularity alignment

- tcmu-runner.spec
Just add a spec file support to make it easy to build with rpmbuild
or with SUSE's open build service.
> runner: add a spec file support

- rbd.c
At the ceph/rbd side object sized IOs are best, but for iSCSI
it is normally going to be too large. In newer linux kernels
the initiator will try to size IOs based on the optimal
size vpd info, and so with the default object size we are
getting 4MB IOs. Even with 10 gig ethernet we can see latencies
in the 1000s of ms and there are no improvements in throughput
with these larger IOs.
This patch just lets the user configure the IO size with the
hw_max_sectors setting.
> rbd: don't override the user requested max sectors

- tcmur_cmd_handler.c
The return value of fuction tcmu_get_dev_max_xfer_len is number of sector, but some functions used it as data size, for example handle_writesam and handle_format_unit functions.
> tcmu:fix error using the return value of function  tcmu_get_dev_max_xfer_length

- alua.c
- main.c
- rbd.c
- tcmu-runner.h
- tcmur_cmd_handler.c
- tcmur_device.c
- tcmur_device.h
If there is no IO in flight or sent when the lock is taken from
from a node, then rbd will not discover the lock has been taken
until it gets IO errors from being blacklisted later. This
will fire off the error handler and force retries.
To avoid that, this patch just updates our lock state when
there is a RTPG or INQUIRY. Normally this would be sent
before switching paths so we can catch the state change then
and prevent the extra retries.
> runner/rbd: update lock state on RTPG/INQUIRY

- rbd.c
There is not need to recheck the size on a resize event
because the calling app, gwcli/ansible, has already set
the ceph side size and then called us. This works around
the issue where if we are blacklisted the size check call
will fail and we end up with a partially updated device.
> rbd: do not recheck size on resize event

- configfs.c
- libtcmu.c
- libtcmu.h
- libtcmu_common.h
- libtcmu_priv.h
- main-syms.txt
- main.c
- tcmu-runner.h
- tcmur_aio.c
- tcmur_cmd_handler.c
- tcmur_device.c
- tcmur_device.h
The following patches allow us to restart runner after it has crashed. They require the tcmu restart patches posted to target-devel (no link yet as spinics has not updated).
> fix restarts from unclean shutdowns

- libtcmu_config.c
If the user has configured log_dir_path in tcmu.conf file,there will be a memory leak.
> libtcmu:fixed memory leaks of log_dir_path

- libtcmu_config.c
If there is no space betwwen the option and the character '=',
after the following while loop, the charactor '=' may be replace by '\0'
and therefore can not be parsed correctly.
> libtcmu:fixed conf file parse error

- alua.c
- main.c
- target.c
- tcmu-runner.h
- tcmur_device.c
- tcmur_device.h
The error log as:
"Could not start implicit transition thread:Cannot allocate memory"
When a joinable thread terminates, its memory resources (thread
descriptor and stack) are not deallocated until another thread
performs pthread_join on it. Therefore, pthread_join must be
called once for each joinable thread created to avoid memory leaks.
Here we will make the lock pthread as detached to avoid this.
Signed-off-by: Zhang Zhuoyu <zhangzhuoyu@cmss.chinamobile.com>
> alua: fix memory leakage when doing the alua implicit transition

- tcmur_cmd_handler.c
If unsupported command was handled by tcmur_cmd_handler, alua implicit
transition have a chance to cause image exclusive-lock threshing between
runners, so do not perform implicit transition if command not supported
Signed-off-by: Zhang Zhuoyu <zhangzhuoyu@cmss.chinamobile.com>
> handler: do not perform implicit transition if command not supported

- CMakeLists.txt
- file_zbc.c
Hello,
I'd like to publish a few commits to ZBC file handler. Most of these are fixes that came about as a result of our internal testing.
Besides the changes listed in the title, this PR contains some minor fixes to tcmu-runner core.
One commit is a fix for a compile error (see the comment attached to the commit). Not sure if anyone else has seen this, but both Damien and me get this error on a fresh install of Fedora 27 unless a specific include is commented out.
Cheers,
Dmitry
> zbc: fix write emulation, change returned sense codes, add install step and more

- configfs.c
Some file like members will with a null char at the end of each
member, just replace it with '\n', except the last one.
> configfs: remove null chars in the string readed from the sys files

- configfs.c
- libtcmu.c
- libtcmu_common.h
This will compatible with the old kernel version which could
not support the ring reset operations.
> libtcmu: add tcmu_is_ring_reset_support support

- libtcmu_config.c
Fix error ret in tcmu_cancel_config_thread.
> conifg: fix error ret

- rbd.c
When cfg two optional options exist at the same time, only the first option can resolve correctly。
> rbd:fix parse cfgstring optional options

- tcmur_aio.c
- tcmur_aio.h
- tcmur_cmd_handler.c
Only fire a single wake up concurrently. If additional AIO
completions arrive while the kernel is being woken up, the
wake up will fire again.
> tcmur: improve batch kernel wake up notifications

- tcmur_device.c
when open device failed，after sleep 1S try to open device again。
> fix the condition of sleep in _tcmu_reopen_dev

- libtcmu.c
These ";" are not needed because we will attach one when everytime we call these macros.
Signed-off-by: Yaowei Bai <baiyaowei@cmss.chinamobile.com>
> libtcmu: drop duplicated ";"

- api.c
- libtcmu_common.h
- main.c
The SAM_STAT_TASK_SET_FULL status code is returned when the logical
unit lacks the resources to accept a received task from an I_T nexus.
For the other errors of the backend storage, we will return NOT READY
status instead of ILLEGAL REQUEST, because returning ILLEGAL REQUEST
would cause immediate IO errors on some initiators, Returning NOT
READY instead means the operations will be retried a finite number of
times and we can survive intermittent errors.
>  tcmu-runner: return the correct scsi proto status to kernel

- alua.c
When the loglevel is in debug mode, for each IO/non-generic SCSI cmd
there will be one debug message output, and there will be aweful
amount of logs full of the log file.
> alua: reduce the debug logs

- main.c
until now there is no check to defend on multiple runs of daemon within
the same node. This patch takes a non blocking lock on 'tcmu.lock' file,
if it succeeds only then daemon is allowed to run, if there is already a
lock on lock-file (taken by some other instance of tcmu-runner) we will exit.
> runner: don't allow multiple instances of daemon to run

- libtcmu_config.c
- libtcmu_log.c
- libtcmu_log.h
- main.c
NOTE: for now this couldn't support the glfs's logging setting, and
the glfs will use the old path .
> config: add the logdir option dynamic reloading support

- libtcmu_config.c
- libtcmu_config.h
make the struct data invisible and fix the log message and clean up the code
> runner: config fix and code clean up

- libtcmu_config.c
> config: fix parse error when there has no space after '='

- file_zbc.c
In the write loop in zbc_write(), tcmu_seek_in_iovec() is called to
consume the command buffer part of the written data. This can lead to
cnsuming entries in the iovec array. However, the pointer iovec is never
updated, potentially leading to a 0 length iovec use while the remaining
nr_lbas is not 0.
Fix this by properly incrementing the iovec pointer by the number of
iovec elements consumed with tcmu_seek_in_iovec().
While at it, also remove the variable iov_cnt and directly use
cmd->iov_cnt as it is used only in one place.
Signed-off-by: Damien Le Moal <damien.lemoal@wdc.com>
> file_zbc: correctly handle iovec seek

- configfs.c
- libtcmu_common.h
- main.c
Will do the netlink reset when starting and just before it could
receive and handle the netlink requests from kernel space.
> tcmu-runner: add reset netlink support

- api.c
- libtcmu_config.c
- main.c
Move the definition of function 'void tcmu_cancel_thread(pthread_t thread)' from 'main.c' to 'api.c', 
so this function can be called by 'main.c', 'libtcmu_config.c' or other module. 
There is no need to implement the same code two or more times.
> To enhance the reuseability of code, move function 'tcmu_cancel_thread' from 'main.c' to 'api.c' .

- tcmu-runner.spec
cp: cannot stat 'LICENSE': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.McXq6H (%doc)
> spec: fix rpm package build error

- tcmu-runner.spec
```
RPM build errors:
Directory not found:
/root/tcmu-runner-orig/extra/rpmbuild/BUILDROOT/tcmu-runner-1.3.0.54.g6684a21-0.el7.centos.x86_64/etc/tcmu
File not found:
/root/tcmu-runner-orig/extra/rpmbuild/BUILDROOT/tcmu-runner-1.3.0.54.g6684a21-0.el7.centos.x86_64/etc/tcmu/tcmu.conf
-----
```
> extra: fix RPM build error

- tcmur_device.c
when function aio_wait_for_empty_queue return non-zero，STPG command should return conversion failed。
> tcmur:fix the initial value of the return var

- tcmur_cmd_handler.c
Incorrect format characters, data overflow。
> tcmur:fix format character on handle_writesame_check

- glfs.c
various loglevels in glusterfs:
GF_LOG_EMERG    = 1  /* system is unusable */
GF_LOG_ALERT    = 2  /* action must be taken immediately */
GF_LOG_CRITICAL = 3  /* critical conditions */
GF_LOG_ERROR    = 4  /* error conditions */
GF_LOG_WARNING  = 5  /* warning conditions */
GF_LOG_NOTICE   = 6  /* normal but significant condition */
GF_LOG_INFO     = 7  /* informational */
GF_LOG_DEBUG    = 8  /* debug-level messages */
GF_LOG_TRACE    = 9  /* trace-level messages */
Thanks to Pranith Kumar K <pkarampu@redhat.com> for pointing this issue.
> glfs: set loglevel to INFO

- api.c
If the valid field has been set to 1, it will be overwritten when setting the sense data.
> libtcmu:fix valid field in sense data

- tcmur_cmd_handler.c
EXTENDED_COPY(LID4) to be supported later。Here，different sa is distinguished, when the SCSI Initiator sends EXTENDED_COPY(LID4) , target reply does not support, instead of the processing exception.
> tcmur: differentiate various sa in the xcopy command

- alua.c
- rbd.c
- tcmu-runner.h
- tcmur_cmd_handler.c
- tcmur_device.c
- tcmur_device.h
1. Update lock state when getting a RTPG or INQUIRY to make sure when a
path is added back after a failover, we re-grab the lock later.
2. Use BUSY instead of ALUA STATE TRANSITION to work around a bug in the linux alua layer.
> runner/rbd: misc implicit failover fixes

- tcmur_device.c
- tcmur_device.h
The following patches fix 2 bugs:
1. We are doing a double close on the handler if the first one is called from a lock or get_tag call, and the second one is called due to escalating the error handler.
2. With rbd we can get into a state where we cannot break the lock and you see -16 errors over and over. The patch for this is optional and may be dropped.
Jason fixed ceph here:
http://tracker.ceph.com/issues/34534
so the tcmu-runner patch would just be tiny optimization for the case where the blacklist is intact, we call lock, that fails and then we do the reopen. With the patch we go right to reopen.
> Fix misc lock/error handler bugs.

- api.c
- file_zbc.c
- glfs.c
- libtcmu_log.h
- main.c
- qcow.c
- rbd.c
- target.c
- tcmur_cmd_handler.c
Add compiler hint
__attribute__ ((format (printf, 4, 5)))
to tcmu_err_message(), et. al. so that the compiler will check the
arguments against the printf format string.
Also change several places in various source files to bring the formats
into conformance with the data types being formatted.
Signed-off-by: David Butterfield <David.Butterfield@wdc.com>
> add checking of logging formats vs. arguments

- api.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- main.c
- rbd.c
- tcmur_cmd_handler.c
For unmap and xcopy the hw max sectors / max xfer len is a little small for handlers like rbd. The following patches allow us to use larger IO sizes for unmap and xcopy while still allowing initiators to send smaller IOs for normal RWs.
> unmap and xcopy IO size fixes

- alua.c
- rbd.c
- tcmu-runner.h
- tcmur_device.c
- tcmur_device.h
Fix a issue commonly seen with Linux initiators where during dm-multipath device initialization the lock bounces between gateways so much tcmu-runner ends up escalating the issue by dropping the iscsi connection by disabling the TPG. This results in probe related IO failing and/or dm-multipath path failures.
> Lock bounce fixes

- file_example.c
- file_optical.c
- qcow.c
- tcmur_aio.c
Instead of requiring handlers with nr_thread > 0 to call
cmd->done we can call in in the io_work_queue, which then
allows for the handlers to pass back any return code.
At the moment handlers can only pass back TCMU_STS_OK
Signed-off-by: Bryant G. Ly <bly@catalogicsoftware.com>
> tcmu: Simplify command completion

- tcmu-runner.spec
* fix the duplicate files error by providing the exact file list
* fix debugsource file error by marking debug_info as nil.
Fixes: #491
Signed-off-by: Amar Tumballi <amarts@redhat.com>
> tcmu-runner.spec: fix the rpm build errors

- libtcmu_log.h
- tcmu.conf
- tcmur_device.c
There is such a record in the log:create_file_output:461: log file path now is '**_/var/log//tcmu-runner.log_**'
> tcmu:fix extra backslash

- api.c
- glfs.c
- libtcmu_common.h
- tcmur_cmd_handler.c
This will invoke zerro fill API due to there has no truely write
same routine yet. Since the writesame emulator in tcmur will do
the same, so it shouldn't be a problem of this.
> glfs: add writesame support

- extra/make_runnerrpms.sh
- tcmu-runner.spec
One can now pass '--without gluster' or '--without rbd' options
to rpmbuild now.
The same has been adopted in make_runnerrpms.sh file.
Signed-off-by: Amar Tumballi <amarts@redhat.com>
> spec-file: further changes to take options to ignore dependencies

- libtcmu.c
> libtcmu: remove useless parameter in remove_device

- libtcmu_config.c
- libtcmu_config.h
- libtcmu_log.c
- libtcmu_log.h
- tcmu.conf
When changing the loglevel in the tcmu.conf for the dynamic logger,
we need to verify it is really working. Currently this hit log is
one INFO level message, which won't work in the ERR and WARN loglevel
cases.
> logger: add critical log level support

- CMakeLists.txt
rsyslog is a *runtime* dependency for the tcmu-runner systemd service.
It doesn't make sense to check for it at build time.
> cmake: drop rsyslog build time check

- tcmu-runner.spec
Fix the build errors.
@mikechristie 
These days @pkalever maybe on PTO and a little busy, I rebased @pkalever's patch to the upstream here.
The patch comes from https://github.com/open-iscsi/tcmu-runner/pull/498.
Thanks.
> libtcmu: carve-out library packages separately

- README.md
- libtcmu_config.c
- libtcmu_config.h
- libtcmu_log.c
- libtcmu_log.h
- main.c
- tcmu.conf
- tcmu.conf_install.cmake.in
> logger: Fix inotify + honor the defaults and precedence of various ways to configure options

- libtcmu_config.c
- main.c
Fixing compiler warnings for -Werror=format-security                             
Warnings Example:                                                                
----------------                                                                 
libtcmu_config.c: In function 'tcmu_conf_set_options':                           
libtcmu_config.c:196:21: error: format not a string literal and \                
no format arguments [-Werror=format-security]                    
TCMU_PARSE_CFG_STR(cfg, log_dir); 
> format-security: fix snprintf usage

- alua.c
- libtcmu_config.c
- main.c
- target.c
- tcmur_cmd_handler.c
- tcmur_device.c
- tcmur_device.h
This patchset fixes a couple bugs in the reopen code path.
1. Accessing freed tcmur_dev_get_private when close has been done but open has not completed.
2. Initiator probe commands are failed during reopening/locking so paths are not automatically added.
3. Misc fixes for pthread function error handling and cleanups
> Misc handler reopen fixes

- tcmur_aio.c
The pthread functions return a positive errno, but we assumed it was negative in the caller dev_added.
> Fix pthread error ret in aio handler

- tcmu-runner.spec
Fedora has a list of valid "short names" to use in the License field.
From https://fedoraproject.org/wiki/Licensing:Main :
Apache 2.0 should be "ASL 2.0"
LGPLv2.1 or greater should be "LGPLv2+"
> rpm: use valid short name licenses in License field

- tcmu-runner.spec
RHEL 4's RPM was the last version to require this.
> rpm: remove %defattr

- tcmu-runner.spec
This section is not needed for modern RPM versions.
> rpm: remove %clean section

- libtcmu.c
- libtcmu_common.h
It's useful for users of libtcmu to be able to query at runtime whether or not the kernel supports out-of-order command (OOOC) completion as this has an impact on how handlers may service SCSI commands. Looking at the kernel version or module version of `target_core_user` is painful as it requires knowing exactly which versions support OOOC, some older kernel modules have the OOOC changes back-ported for example. 
In this commit:
* Expose a new method `tcmu_dev_oooc_supported()` which looks at the mailbox flags to determine whether OOOC is supported.
> Add method to query whether OOOC is supported

- logrotate.conf_install.cmake.in
/etc/cron.daily/logrotate:
error: tcmu-runner.old:1 duplicate log entry for /var/log/tcmu-runner-glfs.log
error: tcmu-runner.old:1 duplicate log entry for /var/log/tcmu-runner.log
> logrotate: fix duplicate log entry error

- main.c
We are hiting the following errors when the lock dir is
not exist:
2019-05-10 05:45:51.186 348 [CRIT] main:981: Starting...
2019-05-10 05:45:51.186 348 [ERROR] main:985: creat(/var/run/lock/tcmu.lock) failed: [No such file or directory]
> lock: create the lock directory when it is not exist

- CMakeLists.txt
- tcmu-runner.spec
Under high-throughput, small IO size workloads, librbd can see up to a
20% performance increase when using tcmalloc instead of the default
glibc allocator.
> Optionally link against tcmalloc for improved small IO performance

- CMakeLists.txt
The minor .so version number should be bumped when backwards compatible
ABI changes are made.
This commit results in the following build output:
libtcmu.so -> libtcmu.so.2
libtcmu.so.2 -> libtcmu.so.2.1
libtcmu.so.2.1
Link: https://www.spinics.net/lists/target-devel/msg17636.html
> cmake: add a minor .so version number to libtcmu

- CMakeLists.txt
> cmake: set '-fno-builtin-XYZ' options when tcmalloc is used

- configfs.c
The ret of function call "read(fd, buf, sizeof(buf))" maybe 0, so the array "buf[ret-1]" will out of bounds.
> configfs: fix index out of bounds

- CMakeLists.txt
Without patch:
$ ldd /usr/bin/tcmu-runner | grep -c libtcmalloc
1
$ ldd /usr/lib64/libtcmu.so | grep -c libtcmalloc
0
$ ldd /usr/lib64/tcmu-runner/handler_file_optical.so | grep -c libtcmalloc
0
$ ldd /usr/lib64/tcmu-runner/handler_file_zbc.so | grep -c libtcmalloc
0
$ ldd /usr/lib64/tcmu-runner/handler_glfs.so | grep -c libtcmalloc
0
With patch:
$ ldd /usr/bin/tcmu-runner | grep libtcmalloc
libtcmalloc.so.4 => /lib64/libtcmalloc.so.4 (0x00007f6d6f5ae000)
$ ldd /usr/lib64/libtcmu.so | grep libtcmalloc
libtcmalloc.so.4 => /lib64/libtcmalloc.so.4 (0x00007f5050952000)
$ ldd /usr/lib64/tcmu-runner/handler_file_optical.so | grep libtcmalloc
libtcmalloc.so.4 => /lib64/libtcmalloc.so.4 (0x00007f6c8286c000)
$ ldd /usr/lib64/tcmu-runner/handler_file_zbc.so | grep libtcmalloc
libtcmalloc.so.4 => …
> tcmu: link libtcmalloc with libtcmu and handlers

- api.c
- libtcmu.c
These logs looks annoying with ERROR tags:
2019-06-14 17:56:33.567 1887 [ERROR] reconfig_device:195 glfs/blockvol:
Handler reconfig failed with error -95.
2019-06-14 17:56:33.569 1887 [ERROR] reconfig_device:195 glfs/blockvol:
Handler reconfig failed with error -95.
2019-06-14 17:56:33.577 1887 [ERROR] reconfig_device:195 glfs/blockvol:
Handler reconfig failed with error -95.
2019-06-14 17:56:33.578 1887 [ERROR] reconfig_device:195 glfs/blockvol:
Handler reconfig failed with error -95.
> tcmu: reconfig_device convert err log to debug

- tcmur_aio.c
- tcmur_cmd_handler.c
Some systems/compilers seem to be loading cmd->done then executing
work->fn. xcopy/unmap/caw set the done function in the work fn so we end
up crasing due to a null pointer.
This has us set the done function before calling the work fn. It also
splits up the line that calls done to make it easier to read.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> runner: fix crash during compound command execution

- tcmur_cmd_handler.c
This very simple fixing won't have any conflict  with https://github.com/open-iscsi/tcmu-runner/pull/568.
> tcmur: remove useless code

- README.md
- consumer.c
- file_example.c
- file_optical.c
- file_zbc.c
- glfs.c
- libtcmu.c
- libtcmu.h
- libtcmu_common.h
- libtcmu_priv.h
- main-syms.txt
- main.c
- qcow.c
- rbd.c
- tcmu-runner.h
- tcmu-synthesizer.c
- tcmur_aio.c
- tcmur_aio.h
- tcmur_cmd_handler.c
- tcmur_cmd_handler.h
- tcmur_device.h
The following patches add infrastructure to allow handlers to cancel/abort commands. The patches currently just log if a command takes longer than tcmur_cmd_time_out seconds. However, for handlers like glfs, we can easily just add a handler callout that the handler can use to clean up/abort a running command.
Notes: Patches are only in the RFC stages.
> Log stuck commands

- darray.h
Sometimes the `&(arr).item[(arr).size]` is a zero pointer. In these
cases decrementing this pointer aka `i` results in something like
0xfffffff8. This is UB, and UB sanitizer in particular reports it as
../iscsi/tcmu-runner/libtcmu.c:563:2: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffff8
In these cases size is `zero` as well, so fix this by simply not running
the cycle when the `size` is zero.
Signed-off-by: Konstantin Kharlamov <Hi-Angel@yandex.ru>
> darray.h: avoid UB when decrementing zero pointer

- tcmu-runner.spec
Since the header files won't be installed, so we need to remove it
from the spec file too.
> spec: fix build error

- scsi.c
commit 117e84c
Author: Yaowei Bai baiyaowei@cmss.chinamobile.com
Date: Tue Sep 18 18:29:44 2018 +0800
libtcmu: move SCSI helpers out of libtcmu
added a regression where we always return the default max unmap len
instead of the handler specific one. This adds back the code to return
the handler specified value.
Fixes issue:
https://github.com/open-iscsi/tcmu-runner/issues/584
> Fix man unmap len reporting

- libtcmu.c
- libtcmu_common.h
Our handler/device needs more information about the tcmu shared memory block (so that it can pass offsets to another process).  This patch adds a function to retrieve that information about the shared memory.
Also updated install_dep.sh so that it works with Debian installations.
> tcmu_dev_get_memory_info()

- libtcmu_log.c
When creating the file output object, we allow it failing and then
the logger should skip it later. If the failing really happen for
some reason, the tcmu-runner daemon will crash.
> logger: fix posible crash when loging to file

- libtcmu_log.c
The log dir path can either come from config file or the command line.
> logger: correct the log message for log dir path

- CMakeLists.txt
Build is failing because of missing `-lpthread` option.
> Fix build on Fedora 31 beta

- extra/install_dep.sh
In `CMakeLists.txt`:
```
find_library(LIBNL_LIB nl-3)
find_library(LIBNL_GENL_LIB nl-genl-3)
set(LIBNL_LIBS
${LIBNL_LIB}
${LIBNL_GENL_LIB}
)
```
So we should install `libnl-genl-3-dev` package, which is not included in `install_dep.sh`.
> extra script: Fix install_dep.sh

- glfs.c
According to the agreement before the fencing patch should be released since 7.6.6, but it seems not. And also in some other OS releases.
> glfs: disable the fencing when it is not support

- libtcmu_log.c
Accidentally I've observed a race between setting of tcmu_logbuf in
log_thread_start() and accessing the variable in tcmu_destroy_log().
When a tcmu-runner instance is already running and a 2nd one is
started on of my test systems I've seen segfaults before the 2nd
instance terminated, e.g.:
log file path now is '/var/log/tcmu-runner.log'
Starting...
tcmu-runner is already running...
Segmentation fault (core dumped)
Further information from coredump is
...
Core was generated by `./tcmu-runner'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0ef972424a in tcmu_destroy_log () at /root/aherrmann/tcmu-runner/libtcmu_log.c:781
781             thread = tcmu_logbuf->thread_id;
[Current thread is 1 (Thread 0x7f0ef9b328c0 (LWP 57799))]
(gdb)
It's an "esoteric" bug, but …
> libtcmu_log: Set tcmu_logbuf before log thread is created

- api.c
Reported by Chris Coulson (chrisccoulson) at:
https://github.com/open-iscsi/tcmu-runner/issues/613
tcmu_cdb_print_info has a fixed size 193 bytes scratch buffer on the stack,
defined here:
void tcmu_cdb_print_info(struct tcmu_device *dev,
const struct tcmulib_cmd *cmd,
const char *info)
{
int i, n, bytes;
char fix[CDB_FIX_SIZE], *buf;
buf = fix;
Further down, it uses sprintf to write some bytes in 2-digit hex format to
buf, with each byte occupying 3 bytes in buf:
for (i = 0, n = 0; i < bytes; i++) {
n += sprintf(buf + n, "%x ", cmd->cdb[i]);
}
To avoid overflowing the stack buffer, there is a check earlier in the
function which performs a heap allocation if bytes is too large:
if (bytes > CDB_FIX_SIZE) {
buf = malloc(CDB_TO_BUF_SIZE(bytes));
if (!buf) {
tcmu_dev_err(dev, "out of …
> Fix possible cdb printing overflow

- alua.c
- libtcmu.c
- target.c
It will overwrite the event worker thread's "ework-thread" name,
which is very important and we will use it to avoid recursive loop.
> worker: do not set thread name in the callback fn

- glfs.c
- main.c
- rbd.c
- tcmu-runner.h
When a device is closing, we will add its entiry address into a list
cache. It may have already been blacklisted by another tcmu node
in reopen case.
And all the stale blacklist entris recorded in the list cache will
be removed in any new comming device doing the open.
Fallback to use lock owner API to store the blacklist entry if the
rados_getaddrs() is not supported, though using the acquire lock
APIs we may miss some blacklist entries.
> rbd: remove all the stale blacklist entries when opening devices 

- file_zbc.c
The supported vpd pages page is required by SPC. It should be included in itself.
This resolves an issue where expected sysfs attributes (specifically scsi_device/vpd_pg0 in new kernels)
is not populated on devices emulated with file_zbc.c.
> Add supported vpd pages to zbc vpd pages

- scsi.c
The else clauses can be dropped when the if section returns.
> scsi: minor simplification of inquiry if/else logic

- tcmur_cmd_handler.c
tcmu-runner can't determine whether the device(s) referred to in XCOPY
Copy Source/Copy Destination (CSCD) descriptors should be accessible to
the initiator via transport settings, ACLs, etc. Consequently, fail
XCOPY requests with CSCD descriptors which refer to any device other
than where the XCOPY request is processed.
References: CVE-2020-28374
Fixes: 9c86bd0 ("tcmur: Add emulate XCOPY command support")
Reviewed-by: Lee Duncan <lduncan@suse.com>
> tcmur: fail cross-device XCOPY requests

- tcmur_cmd_handler.c
This patch-set sits atop the cross-device XCOPY CVE fix submitted via https://github.com/open-iscsi/tcmu-runner/pull/644 .
> XCOPY follow up fixes

- file_zbc.c
Write commands to ZBC devices across zone boundaries shall fail, if the
crossed boundary is between sequential write required zones, or between
a conventional zone and a sequential write required zone. Write commands
across conventional zones shall not fail. Though the commit 87da9fb573a7
("zbc: fix write emulation") relaxed the cross zone boundary check to
allow writes across conventional zones, still such write commands fail.
The commit introduced the helper function zbc_write_check_zones() and
implemented the relaxed boundary check. However, still the old boundary
check is left in zbc_write() and triggers failures for write commands
across conventional zones. To avoid the unnecessary check, remove the
left check code from zbc_write().
Fixes: 87da9fb573a7 ("zbc: fix write emulation") …
> file_zbc: Remove unnecessary zone boundary check

- glfs.c
- rbd.c
- tcmu-runner.h
- tcmur_cmd_handler.c
- tcmur_cmd_handler.h
The write zeroes API will allow the size not to align to the UNMAP
granularity, this can make sure that the specified area will always
be zeroed or discarded. While the discard API will do nothing when
the option rbd_skip_partial_discards is true.
> rbd: switch to use rbd_aio_write_zeroes for unmap

- rbd.c
This will allow the `ceph -s` to classify the daemon names we report
by using the gateway names instead to simplify the `ceph -s` output.
We will keep the service name to make sure it won't break the ceph
dashboard and the third part apps.
Fixes: https://tracker.ceph.com/issues/49057
> rbd: use the new format of the daemon name

- libtcmu_config.c
tcmu-runner doesn't work correctly on Fedora 34 because it
enters an infinite loop while reading the /etc/tcmu/tcmu.conf config
file. The reason is that tcmu_read_config() doesn't check the read()
return value, relying only on errno's value, but the latter should
only be checked when read() returns -1.
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>
> tcmu_read_config(): check read() return value.

- extra/install_dep.sh
The old code will just did nothing if fails to install the first
package.
> install-dep.sh: do not install multiple packages in one single line

- tcmu-runner.spec
Technically the `%{dist}` RPM macro is optional, so Fedora's convention is to use a question mark in the Release field.
https://docs.fedoraproject.org/en-US/packaging-guidelines/DistTag/
Practically speaking, `%{dist}` is almost always defined, so the question mark is not necessary, but this silences a warning in one of Red Hat's internal linters.
> spec: make dist tag optional

- api.c
- libtcmu.c
- libtcmu_common.h
- libtcmu_log.c
- main.c
- tcmur_work.c
I briefly tested it on Alpine Linux and it seems to work.
> Fix compilation on musl libc

- main.c
If the 'manager' is not initialized just skip it.
> main: fix g_object_unref: assertion 'G_IS_OBJECT (object)' failed

- alua.c
- main.c
- target.c
- tcmur_cmd_handler.c
- tcmur_device.c
- tcmur_device.h
The old names were inappropriate any more,  rename them to appropriate ones.
> tcmur_device: rename lock names in tcmur_device struct

- rbd.c
The strtok is not thread safe, there could be several threads will
call the tcmu_rbd_open() at the same time.
> rbd: switch strtok to strtok_r

- libtcmu.c
- libtcmu_common.h
- libtcmu_priv.h
- scsi.c
As discussed in #654, add an api to set write-protect for dev, and set the corresponding parameter when mode sense.
Signed-off-by: liulanzheng <lanzheng.liulz@alibaba-inc.com>
> libtcmu: add support for write protect

- api.c
- be_byteshift.h
In most cases using strict aliasing is undefined behaviour.
Obviously cdb is supposed to be an array of bytes and accessing
any CDB field using strict aliasing leads to misaligned read which
may cause even a crash.
See [here](https://en.cppreference.com/w/c/language/object#Strict_aliasing)
> Use get_unaligned_be*() to avoid UB

- target.c
- tcmur_device.c
To make sure all the in-flight IOs have been finished before flushing the event_work. Or just after we flush the event_work a new timedout IO callback could come and then it will fire a new event work, which may access the device while we are closing the device later.
> tcmur_device: fix racy between reopening devices and reporting events

- tcmur_device.c
After the rbd device being blocklisted it will lost the connection and at the same time will timedout all the IOs. While the tcmu-runner will report a 'lock_lost_cnt' event to ceph cluster. And if during this the device is reopened it will cause the use-after-free bug.
When reopening the device it will hold the 'rdev->rdev_lock' lock and then clear the 'TCMUR_DEV_FLAG_IS_OPEN' flag. And we can check this flag and just skip reporting events if the device is closed.
> tcmur_device: skip reporting events if the device is closed
