file_example.c
- This is a pre-requisite for multithreaded file handler (see #28).
- Yet another fix that could be done is to increment/decrement remaining/offset (when doing pwrite) by 'ret' and not by 'to_copy' which handles partial writes more properly
=> Use pread/pwrite instead of lseek+read/write.

CMakeLists.txt, file_example.c
- Sample async file handler. Build with -DASYNC_FILE_HANDLER to build async file handler.
- Use pread/pwrite instead of lseek+read/write.
=> Sample async file handler

qcow2.h
needs cleanup, jettison lots of unused stuff, but the build needs fixing
=> qcow: missing qcow2.h (adapted from qemu)

main.c
on_check_config receives a user_data pointer, which points to some
element into g_runner_handlers, the array of struct tcmur_handler. This
is not a problem now because the array never resizes (reallocates) once
built, but that is a very fragile assumption and is prune to memory
corruption in the far future.
Instead, save the pointers. All existing callers of
tcmur_register_handler are passing addresses of a static global
variable, so there is no use-after-free risk.  Future callers must be
more careful of the life cycle of handler because they are no longer
copied by value.
=> tcmu-runner: Make g_runner_handlers an array of pointers

README.md
=> README: document cmake with-glfs and with-qcow params

libtcmu.c
In this rare case we should retry instead of giving up.
=> libtcmu: Handle EINTR in start/complete command

api.c, consumer.c, libtcmu.c, libtcmu.h, libtcmu_priv.h, main.c
As the character sequence in 'context'.
=> Global search and replace 'cxt' -> 'ctx'

libtcmu.c
There can be multiple handlers for same type of device trying to handle this
device. Make sure only owner got to open uio device.
=> libtcmu: call check_config before start adding device

glfs.c
Gluster backing files can change size. Do not only read size on open, but
reread it, so READ CAPACITY(16) doesn't return a stale value.
Signed-off-by: Andy Grover <agrover@redhat.com>
=> glfs: Reread size from the device every time read_capacity_16 is called

api.c
https://github.com/open-iscsi/tcmu-runner/issues/76
=> Fix tcmu_emulate_evpd_inquiry() device identification page response marshalling

CMakeLists.txt, file_optical.c
=> tcmu/file_optical: Add File Optical Support

glfs.c
Mostly refactored the code and implement a glfs object cache.
=> Improvements to glfs handler 

.gitignore
=> .gitignore: Ignore cscope.*

libtcmu.c
This patch add two cmd_tail update APIs to simplify the code.
=> libtcmu: add dev and ring buffer cmd_tail update macro APIs

libtcmu_log.c, libtcmu_log.h, main.c
=> tcmu-runner: make a cdb debug info to the same line

main.c
=> tcmu-runner: add possible 12 and 16 bytes CDB debuginfo support.

main.c
=> tcmu-runner:Fix the possible the memory overflow.

.gitignore
=> .gitignore: Ignore *.swp

tcmur_cmd_handler.c
=> Check WRITE_VERIFY lba and length in generic code

libtcmu.c, tcmur_cmd_handler.c, tcmur_cmd_handler.h
Try to simplify the code and do the rhandler->handle_cmd possible NULL pionter check.
=> tcmur: add passthrough handler support

libtcmu.c, libtcmu_common.h, main.c, tcmur_aio.c, tcmur_cmd_handler.c
=> Add tcmu_get_runner_handler helper

tcmur_cmd_handler.c
=> tcmu: Add WRITE_VERIFY_16 command

libtcmu_config.c
The config file will be enhanced later after this.
=> config: Add usage helper and clean up the code style

file_optical.c, main.c, tcmur_cmd_handler.c
The info will be helpful to do the debug.
=> tcmur:  commands not handled will report as not supported

README.md, rbd.c
- Update README for targetcli
- Fix return code in rbd break lock.
=> Misc Cleanup

libtcmu.c, qcow.c
---
These have been missed before.
=> logger: libtcmu/qcow convert to use logger

main.c, tcmur_cmd_handler.c, tcmur_device.h
This should add format unit cmd, I've tried using sg_format but the tool doesnt work for me to test... So i've been waiting on another team to test, but they are taking awhile so if you guys can either test or review that would be great. 
=> tcmu: Add Format Unit

api.c
=> api: mode sense add control page support

CMakeLists.txt, alua.c, alua.h, rbd.c, tcmu-runner.h, tcmur_cmd_handler.c
store drivers have no interest in ISCSI details.
=> refactor out alua specific code out of store driver

api.c, file_optical.c, libtcmu.c, libtcmu_common.h, main.c, qcow.c
Preparing for xcopy patches followed.
=> runner: make the ARRAY_SIZE/min/max macros global

api.c
=> api: Add Block Device Characteristics VPD page(0xb1) support

tcmur_cmd_handler.c
=> tcmur: Add and convert to handle_generic_cbk to simplify the code

README.md
=> README: Update option 2 about writting a tcmu-runner plugin handler

glfs.c, libtcmu_log.c, libtcmu_log.h, main.c
* double free crash fix
* load_module() fix
* log dir path option
* enable gfapi logging
=> crash fix + load_module correction + logging improvements

api.c
=> api: Add Unit Serial Number page (80h) support

glfs.c
=> glfs: implement async read/write/flush versions

api.c
=> api: mode sense add rwrecovery page support

tcmur_cmd_handler.c
For the old code, the WRITE SAME would write the iovec data(from
Data-Out buffer)sector by sector, and it would take to much time
for large size.
This will set the default write length to 1MB, and will round it
up to the device hardware maximum transfer length.
==
This will depend on the PR#155.
=> tcmur: Covert WRITE SAME 16 to async

README.md, alua.c, rbd.c, tcmur_cmd_handler.c
Misc fixes to add compile compat support for rbd and to not always enable ALUA.
=> Misc fixes

glfs.c
* fix indentation
* rename global variable cache -> glfs_cache
* protect cache traffic from race
=> glfs: protect cache traffic from race

rbd.c
The dev->cfgstring is rbd/pool/image before call tcmu_rbd_open function,but it is modifid to rbd/pool after called,the cause is strtok function can modify the input paramter.
=> fix:the dev->cfgstring is modifid in tcmu_rbd_open

main.c
The cfg should released when main function abnormal exit；
also the tcmulib_context should closed after tcmulib_initialize successed whether main function' is normal or abnormal  exit。
=> tcmu-runner: fix the resource released when exception exits in main

rbd.c
=> rbd: use LIBRBD_VERSION() instead of hard code

main.c
=> main: add tcmu_load_config error check and clean up the code

main.c
=> tcmur: free useless darray type handlers memory.

CMakeLists.txt, main-syms.txt, tcmu-runner.h
=> runner: fix handler_init declaring and clean up the code

libtcmu_config.c
=> config: fix memory leak for str type options in tcmu_cfg.

libtcmu.c
=> libtcmu: fix dev_added return check

consumer.c, main.c
Since we do not want to restart poll from kernel
Suggested-by: Mike Christie <mchristi@redhat.com>
=> runner: use ppoll instead of poll

api.c, libtcmu_common.h, rbd.c, tcmu-runner.h, tcmur_cmd_handler.c
=> rbd: Add UNMAP/discard support

qcow.c
Adds flush support to the qcow handler.
Removes O_SYNC flag and unconditionally sets WCE=1 for qcow.
Signed-off-by: Brad Warrum <bwarrum@us.ibm.com>
I've tested the flush support for qcow using the script I've linked below.
There is a comment block at the top of the script that should explain its functionality.
I've tested this with and without the SYNCHRONIZE_CACHE command after a write (sg_sync in the test script), and have also tested with and without the O_SYNC flag set in qcow_open.
[test-qcow-sync.txt](https://github.com/open-iscsi/tcmu-runner/files/1188560/test-qcow-sync.txt)
=> Add flush support for qcow

api.c
=> api: Remove the useless code

qcow.c
The qcow handler's block allocation function originally
checked to make sure the host offset of the cluster being allocated
would not exceed the size specified in the qcow image header.
This is improper behavior, because it counted qcow metadata clusters
towards the virtual image size. This change removes the improper
check from the block allocation function and moves the bound checking
into pwritev.
Signed-off-by: Brad Warrum <bwarrum@us.ibm.com>
=> Fix cluster allocation for nearly-full qcow images

api.c
=> api: make all page handlers static

tcmur_cmd_handler.c
=> tcmur/unmap: fix the NOTE comment

tcmur_cmd_handler.c
=> tcmur: fix and cleanup the unmap handler code

api.c, libtcmu_common.h, tcmur_cmd_handler.c
1, add handle_split_align_unmap helper support
2, write same and write same emulator's UNMAP add align and split feature support
=> WRITE SAME UNMAP add align and split feature support

tcmur_cmd_handler.c
Some trivial changes for the split and align changes.
1. Just some code comment cleanups and function rename.
2. Fix for possible mutex leak.
=> Unmap split fixes

CMakeLists.txt
=> tcmu: bump version to 1.3.0-rc1

libtcmu.c
=> libtcmu: merge resources release code

main.c
=> runner: fix main failure path

main.c
from 'man dlsym':
[...]
the correct way to test for an error is to call dlerror(3) to clear any
old error conditions, then call dlsym(), and then call dlerror(3) again,
saving its return value into a variable, and check whether this saved
value is not NULL.
=> open_handlers: fix dlsym return

rbd.c, target.c
=> make sure only negative error code is returned

rbd.c
=> rbd: merge rbd_finish_aio_read into generic and clean up the code

rbd.c
This is needed to allow an in-memory lookup of librbd performance
metrics on the Ceph dashboard without the need to query the Ceph
cluster or iterate through all available metrics.
=> rbd: include image id within service daemon registration

rbd.c
=> rbd:fix alloc memory for state->conf_path failed in tcmu_rbd_open

glfs.c
$ targetcli /backstores/user:glfs/ ls
o- user:glfs ........................... [Storage Objects: 1]
o- test  [sample@192.168.0.105/test (1.0GiB) activated]
$ targetcli /backstores/user:glfs/test get attribute dev_size
dev_size=1073741824
$ truncate -s +1G /mnt/test
$ ls -l /mnt/test
-rw-------. 1 root root 2147483648 Nov  2 15:05 /mnt/test
$ targetcli /backstores/user:glfs/test set attribute dev_size=2147483648
Parameter dev_size is now '2147483648'.
=> glfs: add support for resize/reconfig of block backend

api.c, libtcmu.c, libtcmu_common.h, libtcmu_priv.h, rbd.c
=> rbd: detect pools associated to SSD device class

rbd.c
Use the rbd readv/writev calls to avoid the memcpy from tcmu
runner buffer to the bounce buffer passed to librbd.
=> rbd: use rbd readv/writev

CMakeLists.txt, api.c, configfs.c, consumer.c, file_optical.c, libtcmu.c, libtcmu_log.c, main.c, string_priv.h, strlcpy.c
This is just misc fixes for bugs found with Coverity covscan.
=> Misc fixes from Coverity covscan

glfs.c
=> glfs: update the glfs config descritions and add usage of creation

glfs.c
1. Let the size checks be handled by glusterfs tools
2. Improve the logging details
=> remove size checks & improve logging details

libtcmu_log.c
Make sure the whole logs are recorded to somewhere before main
loop termination (crashed, SIGINT, ...)
Fix bug : https://bugzilla.redhat.com/show_bug.cgi?id=1475288
=> log: bypass the log ring buffer for file and std outputs

rbd.c
=> rbd:Parsing option 'conf=' error

main.c
=> tcmu-runner:fix free manager

main.c
=> main: fix error goto

libtcmu_config.c
=> config: reset to default values after the options being set

tcmur_cmd_handler.c
=> tcmur: fix ret value in tcmur_dev_update_size

.gitignore
=> gitignore: ignore extra/rpmbuild

alua.c, alua.h
=> alua: allow handlers missing lock routine

main-syms.txt
=> main-syms: remove tcmu_cancel_thread

CMakeLists.txt
=> CMakeList: fix missing file for static library

rbd.c
A Ceph bluestore-backed OSD will automatically associate itself to the "nvme" device class if it detects it's running on an NVMe. This adds support for this additional device class so that the non-rotational SCSI flag is properly configured.
=> rbd: detect pools associated to NVMe device class

main.c
=> main:remove source and decrements the reference count of the GIOChannel

target.c
=> target:delete device node from devs before reopen device

tcmur_cmd_handler.c
Using a sg_compare_and_write -i * -l * -n 0 /dev/* command on Linux host will result in an error.
=> tcmur:fix number of logical blocks is zero in caw command

file_zbc.c
Fix the order of write command checks to ensure that write errors report the
correct asc/ascq. In particular, always check for full zones first.
Signed-off-by: Masato Suzuki <masato.suzuki@wdc.com>
=> file_zbc: Fixed write error checking

alua.c, glfs.c, libtcmu-register.c, libtcmu_config.c, libtcmu_log.c, rbd.c, target.c, tcmur_cmd_handler.c, tcmur_device.c
=> tcmu-runner: fix the code style

tcmur_cmd_handler.c
=> tcmur: fix the minimum of cscd descriptors list length

.gitignore, libtcmu_config.h, libtcmu_log.c
=> logger: notification on changing the options for dynamic reloading

CMakeLists.txt
Signed-off-by: Bryant G. Ly <bly@catalogicsoftware.com>
=> tcmu: Fix CMake to install file_optical

logrotate.conf
=> logrotate: add logrotate support for tcmu-runner-glfs.log

CMakeLists.txt, tcmu-runner.service, tcmu-runner.spec
=> systemd-unit/rpm-spec/cmakeList: add rsyslog to requires list

libtcmu_config.c
=> config: clean up the code

main.c
kmod_module_probe_insert_module maybe failure in load_our_module. The returns: 0 on success, > 0 if stopped by a reason given in @flags or < 0 on failure, and the reason flags as follows:
/* Flags to kmod_module_probe_insert_module() */
enum kmod_probe {
KMOD_PROBE_FORCE_VERMAGIC =		0x00001,
KMOD_PROBE_FORCE_MODVERSION =		0x00002,
KMOD_PROBE_IGNORE_COMMAND =		0x00004,
KMOD_PROBE_IGNORE_LOADED =		0x00008,
KMOD_PROBE_DRY_RUN =			0x00010,
KMOD_PROBE_FAIL_ON_LOADED =		0x00020,
/* codes below can be used in return value, too */
KMOD_PROBE_APPLY_BLACKLIST_ALL =	0x10000,
KMOD_PROBE_APPLY_BLACKLIST =		0x20000,
KMOD_PROBE_APPLY_BLACKLIST_ALIAS_ONLY =	0x40000,
};
So it can't be sensed in main if kmod_module_probe_insert_module return > 0.
=> main: load_our_module maybe failure but can't sensed

libtcmu.c
=> libtcmu: setup_netlink maybe failure but can't sensed

alua.c
Signed-off-by: 李明辉10144360 <li.minghui7@zte.com.cn>
=> Drop sense arg from tcmu_explicit_transition

rbd.c
If the rbd_is_exclusive_lock_owner returns error in tcmu_rbd_has_lock, the caller tcmu_rbd_unlock shouldn't return ok. 
=> rbd: fix the error ret in tcmu_rbd_unlock

configfs.c
=> configfs: clean up the code

tcmur_cmd_handler.c
First bug is in state->refcount where it was incremented after
the call to async_handle_cmd. This can cause issues if
handle_unmap_cbk gets called first before the return to increment
the value of state->refcount.
Second bug is not returning the right error code when doing a
unmap_state_alloc.
Signed-off-by: Bryant G. Ly <bly@catalogicsoftware.com>
=> Fix bugs in unmap

CMakeLists.txt, glfs.c, version.h.in
=> glfs: add gfapi version check

README.md, glfs.c, libtcmu.h, libtcmu_config.c, libtcmu_config.h, libtcmu_log.c, libtcmu_log.h, main.c, tcmu-runner.h
Update README to add uninstall info.
Update the logdir in glfs handler when the logdir is changed.
=> glfs: update the glfs logdir

libtcmu_time.h
=> libtcmu_time: void header file include muti-times

extra/install_dep.sh
=> extra: add gperftools-devel to install_dep script

file_optical.c
=> fbo: fix mutex destroy

tcmur_cmd_handler.c
=> tcmur: fix free of xcopy parse

alua.c
=> alua: fix pthread attr destroy

libtcmu_common.h
=> libtcmu: remove stale fns declaration

glfs.c
=> glfs: check EOF for read

alua.c, file_optical.c, libtcmu.c, libtcmu_common.h, libtcmu_config.c, libtcmu_log.c, main.c, target.c, tcmur_aio.c
This will be helpful when debugging.
=> tcmu-runner: set a name for each pthread

extra/install_dep.sh
Tested on Tumbleweed and SLE15SP1.
Signed-off-by: Andreas Herrmann <aherrmann@suse.com>
=> extra/install_dep.sh: Add support for SUSE

glfs.c
The old code will just fail the glfs device creating, but on the
resize operation, say the backend file expand succees but the if
the config change on tcmu-runner node fails. In this case, after
the node rebooted and retoring it will always fails.
Here will allow the sizes disagree and just apply the new size to
kernel.
=> glfs: allow to load the dev when its size disagree with the backend size

CMakeLists.txt, alua.c, glfs.c, main-syms.txt, main.c, rbd.c, target.c, tcmu-runner.h, tcmur_device.c, tcmur_device.h, tcmur_work.c, tcmur_work.h
> The following patchset fixes several bugs then adds support to track and report errors to handler specific tools.
> 
> Note:
> 
> I'm not working on tcmu-runner anymore. I'm just posting this with the hope it's useful to the next maintainer. You can give me review comments, but I will not be updating the patchset.
This PR is based Mike's previous https://github.com/open-iscsi/tcmu-runner/pull/626 and with some fixings. 
Thank you @mikechristie  for your work for this.
=> Misc fixings and add work thread helper support

CMakeLists.txt
There has mixed using of tabes and white spaces.
=> CMakeList.txt: fix the style and switch tabes to white spaces

rbd.c
=> rbd: fix use-after-free of addr

rbd.c
=> rbd: fix memory leak when fails to get the address

rbd.c
=> rbd: switch to blocklist and make it to be compatible to the old blacklist style
